language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio run
deploy:
  provider: releases
  api_key:
    secure: eKEcdTUT1i858Ela6hRg6Q9WzVyfxfq+dRtd2LacpLp6sC8N5HKMCpQRAmBwD2CBMKQHT3sZlAh9ccM2+iOtXQUjBJbT/1rWVBVSq+9Gjkcw/0XWmhA/pR5ugCNmttyTndcLuxW2Z6B+SVlYUHuBMds4TePt9UJU8z1c+Lj1lANdC/3yDF0TgDHjQT1s7AsroJu3b702Xuo0MZKaYULA+83faHfpGtr9kqD4uCqhTFmEcmWTm7wp/gtb3Do9ZCPDUCHDsYcn/phnoRNat/BjqPmA5NwkxBr5aOWaAZxP9k0xbzcWS9Ls7ZfOubpBv4O3z0MF7J8wrD2aGhBqEgUaR0/+idxSLjtDTtc6vQ8pzaMd2VTEk0a/uU5QykA90F50+uF7Bk5VvO7DS2k3DMs6nWV59HcoNExT/1ZUpwwGwkXF4zMcy743pAGKfMvRHILnGKh6cBkdmPqfk+63LidtiPh8dE0Vwpj33movPbho/+wUCloFtVs3D124PKyYyxAEni1oBeoLipeFg4RwhdUqDW3l/75ZhdQXXmr0PbEBB24BblyKNhJgnL68G14nNPSH4EZG9qXRyI5SR9/fi3s188Ljh3YT1+z0593Jap7qrxydr3gwILJ0AZF5GOLzPWiGzEwBT5jk978P/ePEddy2eqvc5mbOBVhInwFEpbaUDJM=
  file: ".pioenvs/nucleo_f411re/firmware.bin"
  skip_cleanup: true
  on:
    repo: NewJapanRadio/NJU9103_eva_mcu
    all_branches: true
